# Generated by Django 4.0.4 on 2022-05-27 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(default=uuid.UUID('166903fa-b7ae-4248-b621-0b8466ff8330'), max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.CharField(default=uuid.UUID('b64694c0-8f37-480d-b0ea-59bd78891237'), max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
    ]
